// Generated by uniffi-bindgen-cpp for `error_style = "expected"`.
//
// `uniffi::expected` is `std::expected` when the standard library has it and the bundled
// `tl::expected` otherwise. Every translation unit that shares these bindings must agree on
// which one it gets, so build the generated sources with the same standard as their users.
#pragma once

#if defined(__has_include)
#if __has_include(<version>)
#include <version>
#endif
#endif

#if defined(__cpp_lib_expected) && __cpp_lib_expected >= 202211L
#include <expected>

namespace uniffi {
using std::expected;
using std::unexpected;
} // namespace uniffi
#else
{tl_expected}
namespace uniffi {
using tl::expected;
using tl::unexpected;
} // namespace uniffi
#endif
