/* This file was generated by uniffi-bindgen-cpp. C11. */
#ifndef {{ guard }}
#define {{ guard }}

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Conventions:
 * - A call that can fail returns an error, or NULL on success, and writes its result to `out`.
 * - Strings are NUL-terminated UTF-8. Arguments are borrowed for the call.
 * - Everything returned is owned by the caller and released with the matching `_free`.
 * - Async calls return a task and later call `callback` once on the dispatcher.
 */

/**
 * A pending async call. Freeing it cancels the call: once `{{ ns }}_task_free` returns, the
 * callback has finished or will never run. Free every task, including completed ones; it is
 * safe to do so from inside its callback. A dispatcher that refuses work or has shut down
 * abandons the call, and its callback never runs.
 */
typedef struct {{ ns }}_task {{ ns }}_task;

/** Cancels the call if it is still pending and releases the task; NULL is ignored. */
void {{ ns }}_task_free({{ ns }}_task *task);

/** One unit of async work handed to a custom dispatcher. */
typedef struct {{ ns }}_work {{ ns }}_work;

/** Runs the work and releases it. Call it exactly once for every work item accepted. */
void {{ ns }}_work_run({{ ns }}_work *work);

/**
 * Runs async work, and so every callback, somewhere the host chooses, such as its own loop.
 * Both functions may be called from any thread.
 */
typedef struct {{ ns }}_dispatcher {
    /** Queues the work to run later with `{{ ns }}_work_run` and returns true, or returns false to refuse it. */
    bool (*dispatch)(void *user_data, {{ ns }}_work *work);
    /** Stops accepting work, runs what was accepted, and returns once none can still run. */
    void (*shutdown)(void *user_data);
    /** Passed to both functions. */
    void *user_data;
} {{ ns }}_dispatcher;

/**
 * Replaces the default dispatcher thread, before the first async call. The struct is copied.
 * Aborts when called after an async call or a shutdown, or with a NULL function.
 */
void {{ ns }}_set_dispatcher(const {{ ns }}_dispatcher *dispatcher);

/** Stops dispatching for good: pending calls never call back. Call it before unloading. */
void {{ ns }}_shutdown_dispatcher(void);

/** Frees a string returned by this API; NULL is ignored. */
void {{ ns }}_string_free(char *string);

{{ body }}

#ifdef __cplusplus
}
#endif

#endif /* {{ guard }} */