/* This file was generated by uniffi-bindgen-cpp. Compile it as C++17 with {{ namespace }}.cpp. */
#include "{{ namespace }}.h"
#include "{{ namespace }}.hpp"

#include <condition_variable>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <mutex>
#include <optional>
#include <string>
#include <thread>
#include <type_traits>
#include <utility>

namespace {{ namespace }}::c_detail {

// Misuse of the C API, such as a NULL argument, has no error value, so it aborts.
[[noreturn]] inline void fail(const char *message) noexcept {
    ::uniffi::detail::fatal(message);
}

inline void *alloc(size_t size) {
    void *data = std::malloc(size ? size : 1);
    if (!data) {
        fail("out of memory");
    }
    return data;
}

// Moves a C value to the heap, where its `_free` function releases it.
template <typename T>
T *box(T value) {
    static_assert(std::is_trivially_copyable_v<T>, "only C values are boxed");
    auto *out = static_cast<T *>(alloc(sizeof(T)));
    *out = value;
    return out;
}

inline const char *copy_string(const std::string &value) {
    auto *out = static_cast<char *>(alloc(value.size() + 1));
    std::memcpy(out, value.data(), value.size());
    out[value.size()] = '\0';
    return out;
}

// Whether a task's callback may still run. Freeing a task cancels it unless the callback
// already started, and then waits for the callback unless it is the one freeing the task.
class TaskState {
public:
    template <typename Deliver>
    void run(Deliver &&deliver) {
        {
            std::lock_guard<std::mutex> guard(mutex_);
            if (phase_ == Phase::Cancelled) {
                return;
            }
            phase_ = Phase::Running;
            runner_ = std::this_thread::get_id();
        }
        deliver();
        {
            std::lock_guard<std::mutex> guard(mutex_);
            phase_ = Phase::Finished;
        }
        finished_.notify_all();
    }

    void cancel() {
        std::unique_lock<std::mutex> lock(mutex_);
        if (phase_ == Phase::Pending) {
            phase_ = Phase::Cancelled;
        } else if (phase_ == Phase::Running && runner_ != std::this_thread::get_id()) {
            finished_.wait(lock, [this] { return phase_ == Phase::Finished; });
        }
    }

private:
    enum class Phase { Pending, Running, Finished, Cancelled };

    std::mutex mutex_;
    std::condition_variable finished_;
    Phase phase_ = Phase::Pending;
    std::thread::id runner_;
};

} // namespace {{ namespace }}::c_detail

struct {{ ns }}_task {
    std::shared_ptr<::{{ namespace }}::c_detail::TaskState> state;
    // Destroying it cancels the Rust future, which is a no-op once it completed.
    ::uniffi::FutureContinuation continuation;
};

struct {{ ns }}_work {
    ::uniffi::AsyncTask task;
};

{{ objects }}

namespace {{ namespace }}::c_detail {

// Delivers a future's output to `deliver` on the dispatcher, never on the calling thread,
// so a callback cannot run before the call that started it returns its task.
template <typename Future, typename Deliver>
::{{ ns }}_task *spawn(Future future, Deliver deliver) {
    auto state = std::make_shared<TaskState>();
    auto executor = [](::uniffi::AsyncTask task) {
        return ::uniffi::detail::dispatch_async(std::move(task));
    };
    using Output = typename Future::Output;
    if constexpr (std::is_void_v<Output>) {
        auto continuation = std::move(future).then(executor, [state, deliver]() {
            state->run(deliver);
        });
        return new ::{{ ns }}_task{std::move(state), std::move(continuation)};
    } else {
        auto continuation = std::move(future).then(executor, [state, deliver](Output output) {
            state->run([&] { deliver(std::move(output)); });
        });
        return new ::{{ ns }}_task{std::move(state), std::move(continuation)};
    }
}

{{ converters }}

} // namespace {{ namespace }}::c_detail

void {{ ns }}_task_free({{ ns }}_task *task) {
    if (!task) {
        return;
    }
    task->state->cancel();
    delete task;
}

void {{ ns }}_work_run({{ ns }}_work *work) {
    if (!work) {
        ::{{ namespace }}::c_detail::fail("{{ ns }}_work_run: work must not be NULL");
    }
    auto task = std::move(work->task);
    delete work;
    task();
}

void {{ ns }}_set_dispatcher(const {{ ns }}_dispatcher *dispatcher) {
    if (!dispatcher || !dispatcher->dispatch || !dispatcher->shutdown) {
        ::{{ namespace }}::c_detail::fail("{{ ns }}_set_dispatcher: dispatch and shutdown must not be NULL");
    }
    const {{ ns }}_dispatcher copy = *dispatcher;
    ::uniffi::set_async_dispatcher(
        [copy](::uniffi::AsyncTask task) {
            auto *work = new {{ ns }}_work{std::move(task)};
            if (copy.dispatch(copy.user_data, work)) {
                return true;
            }
            delete work;
            return false;
        },
        [copy]() { copy.shutdown(copy.user_data); }
    );
}

void {{ ns }}_shutdown_dispatcher(void) {
    ::uniffi::shutdown_async_dispatcher();
}

void {{ ns }}_string_free(char *string) {
    std::free(string);
}

{{ body }}